### ISSUE TITLE
ERROR in Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by namzee2013** [rd-dev-ukraine/angular-io-datepicker#15]
ERROR in Error encountered resolving symbol values statically. Calling function 'ControlValueAccessorProviderFactory', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DatePicker in /home/nam/Desktop/teikei_chat/tki-frontend/node_modules/angular-io-datepicker/src/datepicker/datePicker.d.ts, resolving symbol DatePicker in /home/nam/Desktop/teikei_chat/tki-frontend/node_modules/angular-io-datepicker/src/datepicker/datePicker.d.ts

**Comment by tobiassalem** [comment]
I have the exact same issue. For the record it works fine with development builds 'ng build'. However, when you do a production build with 'ng build -prod' it fails with the error below every time. Suffice to say, not being able to do production builds is a total dealbreaker. Please advice.

Date: 2017-09-22T07:30:40.830Z
Hash: f6675ae98b573f9375fd
Time: 2481ms
chunk {0} styles.317df2661241c05d1c4c.bundle.css (styles) 358 bytes {3} [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes {3} [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.22b7623ed7c5ac6f9a35.bundle.js (inline) 1.45 kB [entry] [rendered]

ERROR in Error: Error encountered resolving symbol values statically. Calling function 'ControlValueAccessorProviderFactory', function calls
 are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol DatePicker in C:/Us
ers/tobiassa/Projekt/FasitHubFrontend/node_modules/angular-io-datepicker/src/datepicker/datePicker.d.ts, resolving symbol DatePicker in C:/U
sers/tobiassa/Projekt/FasitHubFrontend/node_modules/angular-io-datepicker/src/datepicker/datePicker.d.ts
    at Error (native)
    at syntaxError (C:\Users\tobiassa\Projekt\FasitHubFrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:1725:34)
    at simplifyInContext (C:\Users\tobiassa\Projekt\FasitHubFrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24949:23)
    at StaticReflector.simplify (C:\Users\tobiassa\Projekt\FasitHubFrontend\node_modules\@angular\compiler\bundles\compiler.umd.js:24961:13)

**Comment by AlexGrafic** [comment]
Same Issue. Any updates?

**Comment by Taewa** [comment]
Thanks @AlexGrafic 
When I set `--aot=false` there is no more error.
However, We can't use `aot`if we use angular-io-datepicker?

**Comment by Antony007** [comment]
Same issue. Works if --aot=false. Can't we use the datepicker with aot

**Comment by michaelezehi** [comment]
Hi,

Do we know when this can be fixed? I am having the same issue.

Thanks

**Comment by eugenesaenko** [comment]
@michaelezehi I will fix that on next week.

**Comment by vignesh2694** [comment]
Hi @eugenesaenko  I getting the same error, " --aot=false " may be a solution but the site is slowing down due to this type of build.

 I think " --aot=true  " compiles every thing but "--aot=false " doesn't..   

so i need a fix with --aot=true

**Comment by shivasuriya** [comment]
Yes. Aot is a needful feature and that can't be commented for production builds. So this datepicker should work even though with --aot=true. Please fix.

**Comment by gisarjun** [comment]
Is this bugs is fixed? I am getting this error. What happening? @eugenesaenko
