### ISSUE TITLE
Uncaught Error: Unexpected value 'OverlayModule' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by mjlucero** [rd-dev-ukraine/angular-io-datepicker#39]
WARNING in ./node_modules/angular-io-overlay/node_modules/@angular/core/esm5/cor
e.js
6541:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (C:\Users\mjlucero\Desktop\inform
es-cliente\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (C:\Users\mjlucero\Desktop\
informes-cliente\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (C:\Users\mjlucero\Desktop\informes-cliente\node_modul
es\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (C:\Users\mjlucero\Desktop\informes-cliente\node
_modules\webpack\lib\Compiler.js:502:17)
    at C:\Users\mjlucero\Desktop\informes-cliente\node_modules\tapable\lib\Tapab
le.js:289:11
    at C:\Users\mjlucero\Desktop\informes-cliente\node_modules\html-webpack-plug
in\index.js:60:9
    at tryCatcher (C:\Users\mjlucero\Desktop\informes-cliente\node_modules\blueb
ird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\mjlucero\Desktop\informes-cli
ente\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\mjlucero\Desktop\informes-cliente\node_m
odules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\mjlucero\Desktop\informes-cliente\node_
modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\mjlucero\Desktop\informes-cliente\node_
modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\mjlucero\Desktop\informes-cliente\node_module
s\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\mjlucero\Desktop\informes-cliente\node_modul
es\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\mjlucero\Desktop\informes-cliente\n
ode_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
 @ ./node_modules/angular-io-overlay/node_modules/@angular/core/esm5/core.js
 @ ./node_modules/angular-io-overlay/src/overlay/overlayService.js
 @ ./node_modules/angular-io-overlay/src/overlay/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Compiled with warnings.

**Comment by mjlucero** [comment]
Failed to compile.

Error: Metadata version mismatch for module C:/Users/mjlucero/Desktop/informes-cliente/node_modules/angular-io-overlay/node_modules/@angular/core/core.d.ts, found version 4, expected 3, resolving symbol OverlayModule in C:/Users/mjlucero/Desktop/informes-cliente/node_modules/angular-io-overlay/src/overlay/overlay.module.d.ts, resolving symbol OverlayModule in C:/Users/mjlucero/Desktop/informes-cliente/node_modules/angular-io-overlay/src/overlay/overlay.module.d.ts

**Comment by lucasvst** [comment]
add

"angular-io-overlay": "1.2.7"

to your package.json and you can bypass this error. I think that v1.2.8 is broken now...
