### ISSUE TITLE
Critical dependency: the request of a dependency is an expression...

### ISSUE THREAD

**Issue by lucasvst** [rd-dev-ukraine/angular-io-datepicker#40]
Is this component compatible with angular 5?
I updated my application today and now I have this warning on my build...

```
WARNING in ./node_modules/angular-io-overlay/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/angular-io-overlay/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-io-overlay/src/overlay/overlayComponent.js
 @ ./node_modules/angular-io-overlay/src/overlay/index.js
 @ ./src/app/shared/domain/datepicker/datepicker.module.ts
 @ ./src/app/pages/lms/learning/accounts/balance/balance.component.module.ts
 @ ./src/app/pages/lms/learning/accounts/accounts.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular-io-datepicker/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/angular-io-datepicker/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-io-datepicker/src/datepicker/timeSelector.js
 @ ./node_modules/angular-io-datepicker/src/datepicker/index.js
 @ ./src/app/shared/domain/datepicker/datepicker.module.ts
 @ ./src/app/pages/lms/learning/accounts/balance/balance.component.module.ts
 @ ./src/app/pages/lms/learning/accounts/accounts.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular-io-overlay/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/angular-io-overlay/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-io-overlay/src/overlay/overlayComponent.js
 @ ./node_modules/angular-io-overlay/src/overlay/index.js
 @ ./src/app/shared/domain/datepicker/datepicker.module.ts
 @ ./src/app/pages/lms/learning/accounts/balance/balance.component.module.ts
 @ ./src/app/pages/lms/learning/accounts/accounts.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts

WARNING in ./node_modules/angular-io-datepicker/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compiler.js:502:17)
    at /home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:507:11)
    at processModuleDependencies.err (/home/lucasteles/www/fluig-platform/frontend/src/main/angular/node_modules/webpack/lib/Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/angular-io-datepicker/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/angular-io-datepicker/src/datepicker/timeSelector.js
 @ ./node_modules/angular-io-datepicker/src/datepicker/index.js
 @ ./src/app/shared/domain/datepicker/datepicker.module.ts
 @ ./src/app/pages/lms/learning/accounts/balance/balance.component.module.ts
 @ ./src/app/pages/lms/learning/accounts/accounts.module.ts
 @ ./src/$$_lazy_route_resource lazy
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./src/main.ts
 @ multi ./src/main.ts
```

```
"dependencies": {
    "@angular/common": "~5.2.1",
    "@angular/compiler": "~5.2.1",
    "@angular/core": "~5.2.1",
    "@angular/forms": "~5.2.1",
    "@angular/http": "~5.2.1",
    "@angular/platform-browser": "~5.2.1",
    "@angular/platform-browser-dynamic": "~5.2.1",
    "@angular/router": "~5.2.1",
    "angular-io-datepicker": "^1.3.1",
    "angular-io-overlay": "1.2.7",
   ...
},
"devDependencies": {
    "@angular/cli": "^1.6.4",
    "@angular/compiler-cli": "^5.2.1",
    "typescript": "^2.6.1",
    ...
}
```

**Comment by eugenesaenko** [comment]
Please update angular-io-overlay to 1.2.9
